### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by JinxDojo** [KenshiDRK/Clipper#1]
Should this still work on recent updates of Final Fantasy XI? Is it possible to update?

**Comment by KenshiDRK** [comment]
yes, this still works, but be advised SE seems to have added a detection tool, it seems to only disconect you for now but who knows.

**Comment by JinxDojo** [comment]
Hi there. Thank you for the quick reply and for keeping it maintained/working! (It feels like a rare treat these days to see game tools well-maintained.)

Is it compatible with Ashita? When I load it and hit File>"Select Character", the window pops up for a millisecond then immediately closes before populating. The rest of the main window, of course, remains greyed.

Please let me know if there's something I'm missing. Thanks!

(P.S.: thanks for the warning about SE; fortunately, my usage would be for a private server--and sparingly at that: my thought is actually to use it to *overcome* certain bugs)

**Comment by KenshiDRK** [comment]
Are you running as admin? On private servers you gotta have to rename the loader to pol.exe

**Comment by JinxDojo** [comment]
Just wanted to thank you for the response/support. I was able to get it work when renaming the loader "pol.exe". That might be a good addition to a FAQ in the ReadMe.txt (along with running as admin).

Thanks again!
