### ISSUE TITLE
Speed adjustment broken by 2/09/2022 update

### ISSUE THREAD

**Issue by ceekei87** [KenshiDRK/Clipper#2]
As the title says, I can no longer modify the character movement speed using this software as of the update a few hours ago; the number changes but it has no effect on movement.

JA0wait and GM mode seem to be working.
Character detection and auto disable seem to be working.
I have not tested any forced movement functions or chocobo/maintenance mode.

I don't know if this is still in development, but it'd be great if you could take a look!

**Comment by KenshiDRK** [comment]
Looks like mob struct changed, I'll fix it soon.

**Comment by ceekei87** [comment]
Thank you very much!
Your time and effort on this are greatly appreciated.

**Comment by KenshiDRK** [comment]
Updated the release with a new Configuration.xml file, download again, you'll have to add the exclusions again if you had them.
