### ISSUE TITLE
Unpredictable behavior with new config

### ISSUE THREAD

**Issue by Artician** [KenshiDRK/Clipper#3]
For the past few updates, I 've noticed that several zones that I have used Clipper in extensively in the past have become all but impassible. Typically, the problems arise with any East/west bumps. For a while, it just wouldn't do anything, my character would shake a pixel or two, and nothing else would happen. The Shrine of Ru'Avitau is a big offender, but E/W have been problematic for a while. I updated to the new config, thinking it would fix the issue, and now it either jumps my character a solid 10', or, more often, crashes the game.

**Comment by KenshiDRK** [comment]
the zone is irrelevant, are you on private or retail?

**Comment by Artician** [comment]
Retail. Just checked side by side with old config and new. Old config had same problems as before. Clicking up in the new config just zipped me across the zone. 

Edited for clarity

**Comment by KenshiDRK** [comment]
I just tested and its working good, what are you specting it to do?

**Comment by Artician** [comment]
I expect that when I hit east or west, that I will be nudged east or west
regardless of obstacles, and that when I hit up, I don't get warped across
the map. Does the fact that I play on Ashita make a difference?

**Comment by KenshiDRK** [comment]
it works as expected to me, ashita shouldn't mather but you can always try vanilla and check.

**Comment by KenshiDRK** [comment]
ok got the issue, I guess the Z cord is wrong I'll try to fix soon

**Comment by Artician** [comment]
I was literally just video capturing the error when I saw this. If you
still need the capture, let me know, I can put up an unlisted youtube video

**Comment by KenshiDRK** [comment]
can you try this file? It was completely wrong dunno how it even worked in some cases lol good catch. If its ok I'll update the release
[Clipper.zip](https://github.com/KenshiDRK/Clipper/files/8551057/Clipper.zip)
.

**Comment by Artician** [comment]
Works like a dream now! Tested it in all my trouble areas just to be sure before I posted, just to be thorough. All functions work beautifully, and doors in Sky and other places are now nothing but a firm suggestion. Thanks a bundle!
